index.js

I've created a simple server which is ready for developing!

Initializing Server

---

index.js

Database on localhost connected!

Hristo initializing server

---

index.js
src/middlewares/cors.js

add cors functionality in index.js

add cors.js

---

index.js
src/controllers/authController.js
src/routes.js
src/services/authService.js

Added a routes.js file, with saimple functions for authController.js and authService.js file!

Routing with more folder structure.

---

src/controllers/authController.js
src/controllers/eventsController.js
src/models/Event.js
src/routes.js
src/services/eventsService.js

Added a new route "/events" in route.js file, and create a simple model on database for testing. I've done this with purpose for easier collaborate on code with other back-end fellas! On that said i add a new controller "eventsController.js" and eventsService.js files.

Add new route.

---

src/controllers/authController.js
src/models/User.js
src/services/authService.js

Update user model accurate to the real idea.
Add functionality for register an user with token wich will be send back to the user. The changes are commented becasue will be used later. For now we use only hardcore date.

Work on Register functionality and user model

---

src/controllers/eventsController.js
src/models/Event.js
src/services/eventsService.js

First example of event model is added.

Vision of Event Model added

---

src/models/Organization.js
src/models/User.js
src/services/organizationService.js
src/services/userService.js

Add part of Organization service, controller and model. Still have a lot of questions to finish the task? There is a lot of TODO's wich will be fixed after comunication with the team!

Work on organization structure

---

src/controllers/eventsController.js
src/models/Event.js
src/services/eventsService.js

At       "http://localhost:3030/events/:id" - youcan access exact Event object from data!.
At       "http://localhost:3030/events/" - you can access all Event objects from data.
added additional validation on properties on Event model, also "likes" and "creator" properties was changed to accept object id's of the User model or  Organization model.

Added aditional routes and Event Schema changed!

---

index.js
src/controllers/userController.js
src/models/Organization.js
src/services/userService.js

Fix user login functionality to work correctly, and return correct error if there is.

Login user

---

src/controllers/eventsController.js
src/models/Event.js
src/services/eventsService.js

Added a new request for categories example: http://localhost:3030/events/category/Drag
Changed the name of some functions and added optional price for Events.

New requests for categories added!

---

src/controllers/userController.js
src/models/User.js
src/services/userService.js

fix register functionality to work with real post requst and return token. Remove hardcore data and already fixed comments

Pavel working on register user

---

src/controllers/organizationController.js
src/models/Organization.js
src/services/organizationService.js
src/services/userService.js

Small fixes on UserService (remmove coments, fixed parseToken functionality)
Fixed model of Ogranization, Register and Login funtionality.
Tested register and login

Pavel working on organization register and login

---

src/controllers/userController.js
src/models/User.js
src/services/organizationService.js
src/services/userService.js

Remove "createdEvent" field from user model
Fix return value when make request for register and login for both User and Organization

Pavel dimitrov fixing login and register

---

src/controllers/eventsController.js
src/models/Event.js
src/routes.js
src/services/eventsService.js
src/utils/limitModels.js

1. I've created a pagination util function and pass it into the service "findAllEvents" function.
2. Also added the new titles.
3. created a 404 page route from the wrong path after localhost/3030

Pagination + new title properties added!

---

index.js
src/controllers/eventsController.js
src/middlewares/session.js
src/models/Event.js
src/services/eventsService.js

1.  Session Created
2. Changed Event model according to front-end requirements "visitorPrices"
3. Authorized register created, and error handling for that if the user is admin or organization.

Authorized register created!

---

src/controllers/eventsController.js
src/models/Event.js
src/models/User.js
src/services/eventsService.js

Add requirements for register, for update + fix the first and last name in the User model I've make them optional and changed the hardcodded events properties for testing purposes.

Add requirements for register and update! +

---

src/models/Event.js
src/models/Organization.js
src/models/User.js
src/services/organizationService.js
src/services/userService.js

fix two properties in Event with default value empty string
add default value in firstName and LastName in user model
remove TODO's
add if statement for "deleted" user and organization profile and returning propper error when register or login

Pavel testing and fixing

---

src/controllers/adminController.js
src/controllers/organizationController.js
src/controllers/userController.js
src/middlewares/session.js
src/models/User.js
src/routes.js
src/services/organizationService.js
src/services/userService.js

Add functionality every user and organization to change their data
Add functionality admin user to change users and organizations data
add new route
add new controller and service

P d update user&organization functionality

---

src/controllers/eventsController.js
src/models/Event.js
src/services/eventsService.js

1. Added edit functionality
2. Changed some hardcored data for register event for testing purposes

Edit functionality added

---

src/controllers/adminController.js
src/controllers/eventsController.js
src/services/eventsService.js

1. Fixed checks for empty string in eventsService.js
2. removed admins operation from eventsController
3. added admin operation "editEvent" in admin controller
4. fixed question marks

Fixed checks for empty string

---

src/controllers/eventsController.js
src/services/eventsService.js

Added like dislike functionality for the Event.

Liked event

---

README.md
src/routes.js

Documentation about the server is added. she's will be fixed and updated down the road on development.

Documentation

---

src/controllers/eventController.js
src/models/Event.js
src/services/eventService.js

Create events function changed, now accepts requestBody instead of hardcoded Event. It is tested!

Request body create

---

README.md

Pavel edit organization

---

README.md
src/controllers/organizationController.js
src/controllers/userController.js
src/middlewares/session.js
src/services/organizationService.js
src/services/userService.js
src/utils/parseToken.js

Add functionality for:
1. Edit (info) common information of "Organization". Admin can also edit "isDeleted" property.
2.  Edit email of "Organization". 
3. Edit password of "Organization". Admin also can change the password of "Organization".
Relocateed parseToken functionality to escape repetition of code.
Removed unnecessary comments and added new ones.
Add information about new functionality in README.md

Pavel Dimitrov - Change and Update functionality for editing the Organization

---

src/controllers/userController.js
src/models/User.js
src/routes.js
src/services/userService.js

adding fileds to User model to be used as : 'admin', 'regular' & 'organizator'
add 'createdEvents' and 'phone' fields
After approving of user model, the Organization model will be removed with his controler and services

Pavel refactor User model

---

src/controllers/userController.js
src/models/User.js
src/services/userService.js
src/utils/sharedRegex.js

add new regex for email
add new regex for phone
add validation for length of password

Pavel my liked my events

---

src/controllers/userController.js
src/models/Event.js
src/models/User.js
src/utils/sharedRegex.js

Refactor phone validation in User and Event model.
All phone validation will be executen directly in model
Export  and import in propper places regexes for phone, email and time.
Format code with prettier
Remove unecessary code.

Phone validation

---

src/controllers/eventController.js
src/controllers/userController.js
src/models/User.js
src/services/userService.js

Add validation form Mongo when login
Add editRole functionality

Pavel dimitrov

---

README.md
src/controllers/eventController.js
src/middlewares/cors.js
src/services/eventService.js

1. Check and fix crashes for the BE.
2. Populate the creator property.
3.  Update Documentation for better clarification.
4. Return more accurate error.

Crashes check

---

README.md
src/controllers/userController.js

registerUser => register
loginUser => login
repass => repassword
fix documentation

Refactor user

---

src/controllers/eventController.js
src/services/eventService.js

add route for get request which returns all not approved events

Events for approval

---

README.md
src/controllers/eventController.js
src/services/userService.js

Update documentation
In user service adding check if the requester is approved

Update documentation & add check in user service for not approved admin

---

README.md
src/controllers/userController.js
src/services/userService.js
src/utils/checkDatesAndTime.js
src/utils/securityCheck.js

Fix README
check the requester with real data from DB, not from token
add new route to change delete property of user
fix checkDatesAndTime
add mock code for future refactoring

Edit readme, refactor userController, user Service and checkDatesAndTime

---

README.md
src/controllers/eventController.js
src/controllers/userController.js
src/services/userService.js
src/utils/securityCheck.js

Validate the respective user against the request through external checks

Refactor authorized request checks

---

src/controllers/userController.js
src/services/userService.js

fix logic to work with boolean value

Fix edit deleted and approve user Fn

---

README.md
src/controllers/userController.js
src/models/User.js
src/services/userService.js

1. Get request for retrieving a single user was added.
2. Excluded the "hashedPassword" key from the returned user/users, from userService functions.

Single user get request

---

src/services/userService.js

Fix bug in getUserById Fn

---

README.md
src/controllers/eventController.js
src/services/eventService.js
src/services/userService.js

1. Add checks if user isApproved or isDeleted, to like, edint and register an event.
2. Documentation fixed.

Add more User Checks

---

README.md
src/controllers/eventController.js
src/services/eventService.js

Added new Logic for get Event route, now if event is deleted or unapproved only admin will bale to see it. If event is not deleted and not approved only admin and owner will be able to see it. And if event is approved and not deleted all users will be able to see it. Only if event does not exist in the data no one will be able to see anything.

Get event fix

---

src/controllers/eventController.js
src/services/eventService.js

Add fix for edit event and all places taht i use "findEventById" function.

Edit event fix

---

README.md
src/controllers/userController.js
src/services/userService.js
src/utils/adminsCheck.js

adding functionality for admins waiting for approval
create example function checking admin- only for admins request

Pavel admins for approvals

---

README.md
src/controllers/eventController.js
src/services/eventService.js
src/services/userService.js

1. Add function to delete single event.
2. Prepare second function for deleting multiple events.
3. Add request in controller and function in service for restoring deleted event.
4. Updated documentation.

Hy delete event

---

index.js
src/controllers/eventController.js
src/services/eventService.js
src/services/userService.js

1. add logic for approve/disapprove event
2. fixed error handling
3. add to user service functions more error handling options

Hy approve event

---

README.md
src/controllers/userController.js
src/services/userService.js

1. Adding fn to dissapprove single user when deleted him
2. Adding functionality for multiple edit delete property
3. Fix documentation

Pd approve single approve multiple

---

README.md
src/controllers/userController.js
src/services/eventService.js
src/services/userService.js

1. Create approveDisapproveUsers fn
2. Refactor some checks in deleteRestoreSingleUser, deleteRestoreMultipleUsers approveDisapproveSingleUser, 
3. add comments for fiture development
4. format code
5. update documentation

Pd single approve&multiple approve

---

README.md
package-lock.json
package.json
src/controllers/swaggerEventDocs.js
src/controllers/swaggerUserDocs.js
src/models/Event.js
src/routes.js
swaggerConfig.js

Added swagger Docs to the code
Fixed categories to be at least 1 category in the array

Swagger docs

---

README.md
src/controllers/userController.js
src/services/userService.js

Create:
1. getApprovedOrganizators functionality
2. getApprovedAdmins functionality
3. Update Readme with new rautes

Pd approved admins&approved organizators

---

src/controllers/eventController.js
src/controllers/swaggerEventDocs.js
src/services/eventService.js
src/utils/limitModels.js
swaggerConfig.js

1. Add swagger routes
2. Add more error handling for some routes in controller

Hy event swagger docs

---

README.md
index.js
src/controllers/eventController.js
src/controllers/userController.js
src/middlewares/trimBoddy.js
src/models/Event.js
src/services/emailService.js
src/services/eventService.js
src/services/userService.js
src/utils/getNeededDates.js

1. Add checks for month and year
2. Remove remove unnecessary comment & not useful code
3. Refactor README.MD
4. Refactor getMyFavourites to work wih querry params
5. Left TODO to change the name of findAllEvents FN in eventService

Pd fix comments fix requests

---

src/controllers/eventController.js
src/services/eventService.js

1. fix bug in eventController when edit
2. fix eventForApprove not to return deleted events
3. change isApproved when edit en events

Pd events for approval_editEvent

---

package-lock.json
package.json
src/controllers/userController.js
src/services/emailService.js

fix functionality for resetPassword

Pd forgotten email

---

src/controllers/userController.js
src/services/userService.js

Create a fast fix for the updating password for the user.

Edit user password fix

---

src/services/eventService.js

Change language of error in eventService!

Change language of error in eventService

---

src/controllers/swaggerUserDocs.js
src/controllers/userController.js
src/models/Event.js
src/services/emailService.js
src/services/userService.js

Finished swagger docs (for now)

Hy swagger docs

---

README.md
src/controllers/swaggerUserDocs.js
src/controllers/userController.js
src/services/eventService.js
src/services/userService.js

create functionality for:
-myEventsForApproval
-myUpcomingEvents
-myPastEvents
update documentation

Pd events from organizer

---

src/services/emailService.js
src/services/userService.js
src/utils/parseToken.js

Fix get user by id .env

---

src/controllers/eventController.js
src/controllers/swaggerEventDocs.js
src/controllers/swaggerUserDocs.js
src/controllers/userController.js
src/services/emailService.js
src/services/eventService.js
src/services/userService.js

1. add functionality for "myEventsForApproval", "myUpcomingEvents" and "myPastEvents" to work with query (region, category, search)
2. update emailService to send emails when user/users or event is approved/disapproved

HY_PD+MyEvents_query_emailService

---

src/services/eventService.js

Turn off validation only for this case for this function

Fix Event for delete/approve routes

---

index.js
src/controllers/eventController.js
src/controllers/swaggerEventDocs.js
src/services/eventService.js
src/services/userService.js
src/utils/limitModels.js

1. Sort added for upcoming, past and all events for all places that we use the magic function.\
2. Functionality for getting deleted events by admin added.

Hy sort upcoming/past events

---

index.js
package-lock.json
package.json
src/controllers/userController.js
src/middlewares/session.js
src/services/userService.js
src/utils/parseToken.js

Reverts Getsov/Motorsport-Events-Server#107

Revert "PD_refresh_token"

---

src/controllers/eventController.js
src/controllers/userController.js
src/services/userService.js

add functionality for :
/allOrganizers
/allRegularUsers
/allAdmins
/allUsers
to work with search query

PD_search_query_admins_regular_organizers

---

index.js
src/services/eventService.js
src/services/userService.js
src/utils/limitModels.js

Hy fix past events

---

src/controllers/eventController.js
src/services/eventService.js

1. New fixes for events routes added.

Hy event routes fixes
